env:
  browser: true
  commonjs: true
  es2021: true
extends: 
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/errors
  - plugin:import/warnings
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  allowImportExportEverywhere: true
rules: {}
